version: '3'

services:

  openproject:
    image: openproject/community
    container_name: openproject
    restart: always
    volumes:
      - ./data/app:/var/lib/postgresql/9.4/main
      - ./data/db:/var/db/openproject
    environment:
        SECRET_KEY_BASE: youshouldoverwritethiswithsomethingelse
        VIRTUAL_HOST: project.your-website-one.tld
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: project.your-website-one.tld
        LETSENCRYPT_EMAIL: contact@your-website-one.tld

        # SMTP configuration
        EMAIL_DELIVERY_METHOD: smtp
        SMTP_ADDRESS: smtp.sendgrid.net
        SMTP_PORT: 587
        SMTP_DOMAIN: my.domain.com
        SMTP_AUTHENTICATION: login
        SMTP_ENABLE_STARTTLS_AUTO: true
        SMTP_USER_NAME: "apikey"
        SMTP_PASSWORD: "yourpasswordorapikey"
    expose:
      - "80"
    ports:
      - "8080:80"

networks:
 default:
  external:
   name: nginx-proxy