version: "3"

services:

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.domain.test
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=whoami.domain.test
      - LETSENCRYPT_EMAIL=email@domain.test
    expose:
      - "8000"

networks:
  default:
    external:
      name: web