version: '2'

services:
  mysql:
    image: codions/mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: phpmyadmin
   restart: always
   environment:
    - PMA_ARBITRARY=1
   ports:
    - "8082:80"
   links:
    - mysql