version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:

  adminer:
    image: adminer:4.7.7
    environment:
      - VIRTUAL_HOST=adminer.domain.test
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=adminer.domain.test
      - LETSENCRYPT_EMAIL=email@domain.test
    expose:
      - "8080"
    networks:
      - internal
      - web
    depends_on:
      - mysql
      - postgres