version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - 'mysql:mysql'
    environment:
      - PMA_ARBITRARY=1
      - VIRTUAL_HOST=phpmyadmin.domain.test
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=phpmyadmin.domain.test
      - LETSENCRYPT_EMAIL=email@domain.test
    expose:
      - "80"
    networks:
      - internal
      - web