version: '3'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - VIRTUAL_HOST=phpmyadmin.domain.test
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=phpmyadmin.domain.test
      - LETSENCRYPT_EMAIL=email@domain.test
    expose:
      - "80"

networks:
  default:
    external:
      name: nginx-proxy