version: '3'

services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    # environment:
    #     VIRTUAL_HOST: your-website-one.tld
    #     VIRTUAL_PORT: 9000
    #     LETSENCRYPT_HOST: your-website-one.tld
    #     LETSENCRYPT_EMAIL: email@example.com
    ports:
      - "9000:9000"
    expose:
      - "9000"

networks:
 default:
  external:
   name: nginx-proxy
