version: '3'

services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=portainer.domain.test
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.domain.test
      - LETSENCRYPT_EMAIL=email@domain.test
    expose:
      - "9000"
    ports:
      - "9000:9000"

networks:
  default:
    external:
      name: nginx-proxy