version: '3'

services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=portainer.domain.test
      - VIRTUAL_PORT=9443
      - LETSENCRYPT_HOST=portainer.domain.test
      - LETSENCRYPT_EMAIL=email@domain.test
    expose:
      - "9443"
    ports:
      - "8000:8000"
      - "9443:9443"

networks:
  default:
    external:
      name: nginx-proxy