version: "3"

services:

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      - VIRTUAL_HOST=adminer.yourdomain.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=adminer.yourdomain.com
      - LETSENCRYPT_EMAIL=email@yourdomain.com
    expose:
      - "8080"

networks:
  default:
    external:
      name: nginx-proxy