version: '3'
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        ports: 
            - "9915:3306"
        environment:
            MYSQL_ROOT_PASSWORD: yourpasswd
        volumes:
            - ./data:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        links: 
            - mysql:mysql
        environment:
            PMA_ARBITRARY: 1
            VIRTUAL_HOST: phpmyadmin.your-website-one.tld
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: phpmyadmin.your-website-one.tld
            LETSENCRYPT_EMAIL: contact@your-website-one.tld
        expose:
          - "80"

networks:
  default:
    external:
      name: nginx-proxy