version: '2'

services:

  portainer.app:
    image: portainer/portainer
    container_name: portainer.app
    restart: always
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"